#!/bin/bash
# This is the script that shuold be run from within the install

# Language  (ENGLISH)
sed -i 's/^#en_US.UTF-8/en_US.UTF-8/' /etc/locale.gen
locale.gen
echo LANG=en_US.UTF-8 > /etc/locale.conf
export LANG=en_US.UTF-8

# Region for timing and the hardware clock

ln -s $location > /etc/localtime
hwclock --systohc --utc

# Set Hostname
echo "arch" > /etc/hostname

# Set trim, for SSDs
if [ "$ssd" == "y" ] || [ "$ssd" == "y" ]
then
  systemctl enable fstrim.timer
fi

# Allow use of 32-bit software
# arch-chroot /mnt sed -i 's/^#\[multilib\]/\[multilib\]' /etc/pacman.conf
# arch-chroot /mnt sed -i 's/^#Include = /etc/pacman.d/mirrorlist' /etc/pacman.conf

# Set up root and user information such as password
echo $'$rootPassword1\n$rootPassword1'|passwd
useradd -m -g users -G wheel,storage,power -s /bin/bash $username
echo $'$rootPassword1\n$rootPassword1'|passwd $username

# Wheel group for command and need sudo password
sed -i 's/^#\s%wheel\sALL=\(ALL\)\sALL$/%wheel\sALL=\(ALL\)\sALL/' /etc/sudoers.tmp
echo "Defaults rootpw" >> /etc/sudoers.tmp


# Set up bootloader
bootctl install
echo "title Arch Linux" >> /boot/loader/entries/arch.conf
echo "linux vmlinuz-linux" >> /boot/loader/entries/arch.conf
if [ "$intelCPU" == "y" ] || [ "$intelCPU" == "y" ]
then
  pacman -S intel-ucode
  echo "initrd /intel-ucode.img" >> /boot/loader/entries/arch.conf
fi
echo "initrd /initranfs-linux.img" >> /boot/loader/entries/arch.conf
echo "options root=PARTUUID=$(blkid -s PARTUUID -o value /dev/$filePartitionID) rw" >> /boot/loader/entries/arch.conf

# The networking
yes|pacman -S networkmanager
systemctl enable NetworkManager.service

# Downloads
yes|pacman -Syu  atom bash-completion cronie curl dconf dconf-editor efibootmgr flashplugin \
gcc gdm gimp git gnome-desktop \
gnome-tweak-tool grep hunspell-en hyphen-en libreoffice linux-lts linux-lts-headers mono ntp ocaml otf-overpass perl pip powertop \
python ruby sshd unzip vim virtualbox virtualbox-guest-utils vlc \
wget

# atom - text editor
# bash-completion - makes autocomplete better
# cronie - used for crone jobs
# curl - tool to download
# dconf - tool for settings
# dconf-editor - gui tool for dconf
# efibootmgr - required for efi grub
# flashplugin - browser plugin
# gcc - compiler
# gdm - the display manager for gnome
# gimp - photo editor
# git - versioning software
# gnome-desktop - the desktop environment
# gnome-tweak-tool - settings tool for gnome
# grep - search for a string
# hunspell-en - for spelling/grammar
# hyphen-en - for spelling/grammar
# libreoffice - text editor suite
# linux-lts - the long term support kernel version
# linux-lts-headers - the long term support kernel version
# mono - compiler
# ntp - used to synchronize the clock
# ocaml - programming language
# otf-overpass - a font package
# perl - programming language
# pip - package manager for python
# powertop - power manager
# python - programming language
# ruby - programming language
# sshd - used for secure shell
# unzip - command to unzip
# vim - text editor
# virtualbox - a virtual machine tool
# virtualbox - guest-utils - a tool for virtual machines
# vlc - media player
# wget - tool to download

# Install packages from the AUR

git clone https://aur.archlinux.org/yaourt.git
cd yaourt
makepkg -sic
cd ..
rm -rf yaourt
yaourt --noconfirm google-chrome
yaourt --noconfirm papirus-icon-theme-git
yaourt --noconfirm papirus-folders-git
papirus-folders -C black
yaourt --noconfirm gtk-theme-arc-grey
yaourt --noconfirm ttf-ms-fonts

yaourt --noconfirm capitaine-cursors
sudo cp /usr/share/icons/capitaine-cursors/cursors/dnd-move \
/usr/share/icons/capitaine-cursors/cursors/fleur
sudo rm -f /usr/share/icons/capitaine-cursors/cursors/size_bdiag
sudo rm -f /usr/share/icons/capitaine-cursors/cursors/size_fdiag
sudo rm -f /usr/share/icons/capitaine-cursors/cursors/size_hor
sudo rm -f /usr/share/icons/capitaine-cursors/cursors/size_ver
# Yaourt is a manager for the AUR
# Google is a browser
# Papirus have the best icons
# Papirus-folders allows one to change the folder color
# arc-grey gnome theme
# Font for microsoft
# capitaine is a curosor
# edit the cursor icons to look better

# Create icons for the desktop
ln -s ~/Pictures ~/Desktop/Pictures
gio set ~/Desktop/Pictures metadata::custom-icon \
file:///usr/share/icons/Papirus/48x48/places/folder-black-pictures.svg

ln -s ~/Documents ~/Desktop/Documents
gio set ~/Desktop/Documents metadata::custom-icon \
file:///usr/share/icons/Papirus/48x48/places/folder-black-documents.svg

ln -s ~/Downloads ~/Desktop/Downloads
gio set ~/Desktop/Downloads metadata::custom-icon \
file:///usr/share/icons/Papirus/48x48/places/folder-black-download.svg

gsettings set org.gnome.nautilus.icon-view default-zoom-level 'standard'

# Set up github

# Set up grub
grub-mkconfig -o /boot/grub/grub.cfg
grub-install /dev/$drive

# Set up github
if [ "$githubChoice" == "y" ] || [ "$githubChoice" == "Y" ]
then
  git config --global user.name $githubUsername
  git config --global user.email $githubEmail
fi

# Create the .vimrc
echo "command W w \"allow caps
command Wq wq \"allow caps
command WQ wq \"allow caps
command Q q \"allow caps

syntax on \"nice coloring of syntax
set number \"adds line numbers
set expandtab \"spaces for tabs
set sw=4 \"default to tabstop
set tabstop=4 \"visual spaces per tab
set softtabstop=4 \"tab spaces while editing
set wildmenu \"visual autocomplete
set incsearch \"search as characters are entered
set hlsearch \"highlight matches
set backspace=indent,eol,start \"allows use of backspace
set autoindent \"new lines inherit the indent from the previous lines
set history=50 \"improves the undo property
set background=light
set termguicolors
colorscheme PaperColor
set background=dark" > /home/$username/.vimrc

# Gnome settings tweaks
dconf write /org/gnome/desktop/peripherals/touchpad/natural-scroll true # Turn off natural scrolling
dconf write /org/gnome/desktop/interface/enable-animations false # no animations
dconf write /org/gnome/shell/overrides/dynamic-workspaces true # dynamic number of workspaces
dconf writre /org/gnome/shell/overrides/workspaces-only-on-primary false #wokspaces on mltiple dispalces
dconf write /org/gnome/desktop/peripherals/touchpad/speed 0.45 # Set trackpad speed
dconf write /org/gnome/desktop/search-providers/disabled "['org.gnome.Epiphany.desktop']" # Do not search Internet
dconf write /org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-type "'suspend'" # set suspend information
dconf write /org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-timeout 900
dconf write /org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type "'suspend'"
dconf write /org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-timeout 1800
dconf write /org/gnome/settings-daemon/plugins/power/power-button-action "'suspend'"
dconf write /org/gnome/desktop/wm/preferences/focus-mode "'click'" # for focusing
dconf write /org/gnome/desktop/interface/gtk-theme "'Arc-Darker'" # Set application theeme
dconf write /org/gnome/desktop/interface/cursor-theme "'capitaine-cursors'" # Set cursor theme
dconf write /org/gnome/desktop/interface/icon-theme "'Papirus'" # Set the icon theme
dconf write /org/gnome/desktop/background/show-desktop-icons true # show desktop theeme
dconf write /org/gnome/nautilus/preferences/search-filter-time-type "'last_modified'"
dconf write /org/gnome/nautilus/desktop/home-icon-visible true # Show home folder
dconf write /org/gnome/desktop/wm/preferences/titlebar-font "'Overpass 12'" # Set fonts
dconf write /org/gnome/desktop/wm/preferences/titlebar-font "'Overpass 12'"
dconf write /org/gnome/desktop/interface/document-font-name "'Overpass 11'"
dconf write /org/gnome/desktop/interface/monospace-font-name "'Overpass Mono 11'"

dconf write /org/gnome/desktop/peripherals/touchpad/disable-while-typing true # no trackpad when typing

dconf write /org/gnome/settings-daemon/plugins/xsettings/overrides "{'Gtk/ShellShowsAppMenu': <1>}" # Show application menu top bar
dconf write /org/gnome/desktop/interface/show-battery-percentage true # Show battery percentage top bar

dconf write /org/gnome/desktop/wm/preferences/button-layout "'appmenu:minimize,maximize,close'" # Right side of windows
